### ISSUE TITLE
'pip install goreutilities' does not install the correct (latest) version and breaks Python 3 support

### ISSUE THREAD

**Issue by epgui** [eyurtsev/FlowCytometryTools#16]
It seems the version of goreutils being installed on my machine (0.5.0) is the same version specified here https://bitbucket.org/gorelab/goreutilities/src/2c4224c5820a202394aa16a42afa581a73e5dc56/GoreUtilities/_version.py?at=master&fileviewer=file-view-default

However, the copy of the source installed in my virtualenv does not match the most up to date version of the source code. The version I get breaks in python 3.

**Comment by eyurtsev** [comment]
Thanks for letting me know. The package itself is not python 3 compatible, so I'm not sure whether the dependency is going to resolve the issue. I'll try to look into it when I have free time, but I'm not working with flow data anymore.

In the meanwhile, I suggest running with with python 2.7 interpreter. If you're using virtualenv, you can create an environment that uses python2.7 as the default interpreter (virtualenv --help, virtualenv -p)

**Comment by epgui** [comment]
I'm not sure yet what other parts are incompatible with python 3, but I think it would be important to keep this up to date. There are a few more features I'd like to work on myself (clustering, gating, fingerprinting, noise reduction and curve fitting...), and I'd be more willing to spend time on this if it didn't depend on other unmaintained packages. I've been trying to decide whether I should just pick up the fcsreader and build from there, or whether it was easier to just work on FlowCytometryTools.

**Comment by eyurtsev** [comment]
I'm not maintaining this repository very actively, and don't want to end up blocking your ability to develop -- so perhaps grab the bits of code that you need (fcsreader / transformations from FlowCytometryTools) and build on top of them as you suggested.  

If you get to a point where you find that the tools would be useful to integrate directly into flowcytometrytools, i'll always be happy to accept a PR :)

I'll try to resolve the issues with GoreUtilities, but it'll probably take sometime since I don't have much free time to dev

**Comment by eyurtsev** [comment]
I merged your PR request and made a few fixes -- There's probably a few errors remaining still on master (test coverage isn't great). 

Will attempt to verify master this weekend and close issue

**Comment by eyurtsev** [comment]
Released an updated version of the package on pypi, so closing this issue
