### ISSUE TITLE
Bi-Exponential scale/trasformation

### ISSUE THREAD

**Issue by sinnamone** [eyurtsev/FlowCytometryTools#26]
Hi, 

I'm wondering if there's a possibility to reproduce with this package the bi-exponential transformation/scaling that is implemented in flow-jo.

Thanks in advance,

Best regard

Simone

**Comment by eyurtsev** [comment]
Hi Simone, 

The available transformations are linear, hlog, glog, tlog. 

It's been a really long time since I've thought about these (~7 years+). So i don't remember whether a bi-exponential scale is one of the existing non-linear transformations under a different name or whether it was largely unnecessary given the presence of the hlog/glog/tlog transforms. 

If you have the time you can try to read through the papers referenced in the documentation (attaching here for ease):

* Bagwell. Cytometry Part A, 2005.
* Parks, Roederer, and Moore. Cytometry Part A, 2006.
* Trotter, Joseph. In Current Protocols in Cytometry. John Wiley & Sons, Inc., 2001.
